# Generated by Django 6.0.3 on 2026-03-29 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0003_game_steam_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='nintendo_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='playstation_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='xbox_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
