# Generated by Django 6.0.3 on 2026-03-29 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0004_game_nintendo_url_game_playstation_url_game_xbox_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
