# Generated by Django 6.0.3 on 2026-03-29 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0002_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='steam_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
