# Generated by Django 6.0.1 on 2026-03-30 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0005_game_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='trailer_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
