# Generated by Django 6.0.1 on 2026-04-02 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0006_game_trailer_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='hltb_completionist',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='hltb_extra',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='hltb_main',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
