# Generated by Django 6.0.1 on 2026-04-05 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0007_game_hltb_completionist_game_hltb_extra_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='developers',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
