# Generated by Django 6.0.1 on 2026-04-19 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0008_game_developers'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='steam_owners',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='steam_review_score',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='steam_screenshots',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='steam_total_reviews',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
