# Generated by Django 6.0.1 on 2026-04-19 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0009_game_steam_owners_game_steam_review_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='steam_review_percentage',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
